# Generated by Django 5.1.4 on 2024-12-20 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='income',
            old_name='user_id',
            new_name='user',
        ),
    ]
