# Generated by Django 5.1.4 on 2024-12-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_rename_user_id_income_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='income',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
